# Generated by Django 4.0.1 on 2022-04-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addcourse',
            new_name='addfile',
        ),
    ]
